// Generated by CoffeeScript 1.7.1
var bookly;

bookly = bookly || {};

bookly.bookApp = angular.module('bookApp, []');

bookly.BooksController = function($scope) {
  $scope.books = books;
  $scope.cart = [];
  $scope.addToCart = function(book) {
    $scope.cart.push(book);
  };
  $scope.cartTotal = function(cart) {
    var books, total, _i, _len;
    total = 0.0;
    for (_i = 0, _len = cart.length; _i < _len; _i++) {
      books = cart[_i];
      (function(book) {
        total = total + book.price;
      });
    }
    return total;
  };
  $scope.emptyCart = function(cart) {
    $scope.cart = [];
  };
  $scope.quantify = function(cart, book_id) {
    var book, items;
    items = (function() {
      var _i, _len, _results;
      _results = [];
      for (_i = 0, _len = cart.length; _i < _len; _i++) {
        book = cart[_i];
        if (book.id === book_id) {
          _results.push(book);
        }
      }
      return _results;
    })();
    return items.length;
  };
};
